name: MobileBackPack
version: '${project.version}'
main: me.maxi.mobilebackpack.Main
api-version: 1.19
authors: [ FreshFoxy ]
website: https://mythria.net
commands:
  givebackpack:
  upgradepackback:
